#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Client.Resource", IsApplication=true)]

namespace Client
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.0.99.109")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F010000
			public const int btnBack = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int btnConnect = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int btnCreate = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int btnLogout = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int btnShutdown = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int btnSign = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int btnSignUp = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int btnSleep = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int btnTakeScreen = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int edtEmail = 2130771977;
			
			// aapt resource value: 0x7F01000D
			public const int edtfullname = 2130771981;
			
			// aapt resource value: 0x7F01000A
			public const int edtIpAddress = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int edtMobile = 2130771979;
			
			// aapt resource value: 0x7F01000E
			public const int edtpassword = 2130771982;
			
			// aapt resource value: 0x7F01000C
			public const int edtPort = 2130771980;
			
			// aapt resource value: 0x7F01000F
			public const int edtusername = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int imageView = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int textView1 = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int txtOr = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int txtpassword = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int txtusername = 2130771988;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F020000
			public const int Connect = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int Control = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int Main = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int SignUp = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
